### ISSUE TITLE
Curve PoolX3 topic `RemoveLiquidityOne(indexed address,uint256,uint256,uint256)`

### ISSUE THREAD

**Issue by undermethod** [Opty-Fi/megagraph#36]
Can you please confirm if this needs updating?
https://github.com/Opty-Fi/megagraph/blob/3848b7b4a0496e0350493cba0bb08d99f9fa832d/src/Curve/abis/PoolX3.json#L42

I believe needs to be:
```
      { "type": "uint256", "name": "coin_amount", "indexed": false },
      { "type": "uint256", "name": "token_supply", "indexed": false }
```
as I think the `token_supply` is missing.

**Comment by uwe** [comment]
I trimmed down the ABIs in https://github.com/Opty-Fi/megagraph/pull/30 to only contain the events and calls that we use. This inconsistency between `PoolX2` and `PoolX3` was there before.

I looked up two Curve pools (X2 and X3) - the difference is really there. So this seems to be correct (but strange nevertheless).

Did you find a counter-example? I did not verify all pools.

**Comment by undermethod** [comment]
I've found that contracts `0xDeBF20617708857ebe4F679508E7b7863a8A8EeE` and `0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7` are missing `TokenExchangeUnderlying(indexed address buyer, int256 sold_id, uint256 tokens_sold, int256 bought_id, uint256 tokens_bought)`, `uint256 token_supply` of `RemoveLiquidityOne` as before, `CommitNewAdmin(indexed uint256 deadline, indexed address admin)`, `NewAdmin(indexed address admin)`, `CommitNewFee(indexed uint256 deadline, uint256 fee, uint256 admin_fee)`, `NewFee(uint256 fee, uint256 admin_fee)`, `RampA(uint256 old_A, uint256 new_A, uint256 initial_time, uint256 future_time)`, and `StopRampA(uint256 A, uint256 t)`. Both of which are X3, not X2. So I'm not sure yet why this discrepancy exists.

**Comment by uwe** [comment]
Thanks. I do agree with the first point (and will add a PR to fix this).

But there is no `token_supply` in `RemoveLiquidityOne` for https://etherscan.io/address/0xDeBF20617708857ebe4F679508E7b7863a8A8EeE#code (see ABI and source code line 51).

All the other events are not needed for megagraph and have been removed in #30.

**Comment by uwe** [comment]
https://etherscan.io/address/0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7#code for example does not have the `TokenExchangeUnderlying` event.
